### ISSUE TITLE
How to send Headers/Body that aren't &'static str

### ISSUE THREAD

**Issue by alshdavid** [Xudong-Huang/may_minihttp#15]
Hi, the `Response.header()` and `Response.body()` arguments take an `&'static  str`.

How do you use a `String` as a response type without leaking a value?

This doesn't work:
```rust
impl HttpService for ServerService {
  fn call(
    &mut self,
    req: Request,
    rsp: &mut Response,
  ) -> io::Result<()> {
    let value = String::from("hello world");
    rsp.body(&value);
    Ok(())
  }
}
```

**Comment by Xudong-Huang** [comment]
I think this is answered in #14

**Comment by kobutri** [comment]
That works for the body, but what about the headers, e.g. when I want to use `Set-Cookie`
