### ISSUE TITLE
[Feature Request] Add support for receiving binary data from body

### ISSUE THREAD

**Issue by Davilarek** [Xudong-Huang/may_minihttp#16]
Hello, I was making my project using this package and I noticed weird issues when receiving binary data from a POST request.
The results vary depending on the file submitted.
In some cases I was getting `failed to parse http request: NewLine`, in another case I got hit by `failed to parse http request: Token` and sometimes even a rust panic.
```
thread '<unnamed>' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/may_minihttp-0.1.9/src/request.rs:38:45:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Here's the code I'm using:
```rust
let mut buffer = [0u8; 1024];
loop {
    let read_result = req_body.read(&mut buffer);
    if read_result.is_err() {
        error_reason = crate::handlers::errors::WRITE_ERROR;
        break;
    }
    let bytes_read = read_result.ok().unwrap();
    if bytes_read == 0 {
        break;
    }
    let res2 = file.write_all(&buffer[..bytes_read]);
    if res2.is_err() {
        error_reason = crate::handlers::errors::WRITE_ERROR;
    }
}
```
This doesn't seem to happen with text files.
Thanks

**Comment by Xudong-Huang** [comment]
Strange. Could you please try to increase the may stack size to a larger value and try again?
```rust
pub fn main() {                                                                                                                                     
        may::config().set_stack_size(0x4000);
        ......
}
```

**Comment by Xudong-Huang** [comment]
Could you please try the latest master code?
Also you may need to increase the stack size due to 1 KB buffer on the stack.

Thanks

**Comment by Xudong-Huang** [comment]
I will release a new version if the bug is gone

**Comment by Davilarek** [comment]
I'm sorry, I can't test it right now

**Comment by Xudong-Huang** [comment]
just take your time 😄

**Comment by Davilarek** [comment]
Looks like it works now, thanks!
