### ISSUE TITLE
POST Example

### ISSUE THREAD

**Issue by codecandy2015** [Xudong-Huang/may_minihttp#2]
Hi,
I am trying to do a simple POST. I tried this,
`match (req.method(), req.path()) {
            ("GET", "/json") => {
                rsp.header("Content-Type: application/json");
                serde_json::to_writer(
                    BodyWriter(rsp.body_mut()),
                    &HelloMessage {
                        message: "Hello, World!",
                    },
                )?;
            },
            ("POST", "/json") => {
                rsp.header("Content-Type: application/json");
                serde_json::to_writer(
                    BodyWriter(rsp.body_mut()),
                    req.data(),
                )?;
            },
            ("GET", "/plaintext") => {
                rsp.header("Content-Type: text/plain").body("Hello, World!");
            },
            _ => {
                rsp.status_code("404", "Not Found");
            },
        }`

However, I am not able to access the request Body. Do you have any suggestions perhaps ?
Kind regards
Savi

**Comment by janderadutra** [comment]
pub fn body(&self) -> &[u8] {
        unimplemented!()
    }
I wanted to use this api

**Comment by evmer** [comment]
I submitted a pull request to add the implementation of the body() api #3

**Comment by janderadutra** [comment]
Thanks!!

**Comment by Xudong-Huang** [comment]
I think we can close this now. the request has a body() API which impl `io::Read`/`io::BufRead` to read out the body
